# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersrights',
            name='right',
        ),
        migrations.AddField(
            model_name='usersrights',
            name='rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.RightsAccess'),
        ),
    ]
